# Generated by Django 4.1 on 2023-09-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailSender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
    ]
