# Generated by Django 4.1 on 2023-09-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailSender', '0002_remove_employee_created_at_remove_event_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('logs', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
